variables:
  SOFT_VERSION: '1.0'
  SOFT_VERSION_EXT: 'beta'
  PRO_SHORT: 'assistant'

before_script:
  - pwd
after_script:
  - sudo rm -rf ${CI_PROJECT_DIR}/target

stages:
  - java-package
  - mariadb
  - mongodb
  - docker-push
  - java-to-qa
  - mariadb-to-qa
  - mongodb-to-qa

#java编译
java-package:
  stage: java-package
  script:
    - /home/gitlab-runner/shell/dockerbuild.sh ${CI_PROJECT_DIR} ${CI_PROJECT_NAME} ${CI_COMMIT_SHA} ${SOFT_VERSION} ${SOFT_VERSION_EXT}
  tags:
    - facecompare
  only:
    - triggers

#mariadb初始化脚本
mariadb:
  stage: mariadb
  script:
    - /home/gitlab-runner/shell/mariadb.sh ${CI_PROJECT_DIR} ${CI_PROJECT_NAME} ${CI_COMMIT_SHA} ${SOFT_VERSION} ${SOFT_VERSION_EXT}
  tags:
    - facecompare
  only:
    - triggers

#mongodb初始化脚本
mongodb:
  stage: mongodb
  script:
    - /home/gitlab-runner/shell/mongodb.sh ${CI_PROJECT_DIR} ${CI_PROJECT_NAME} ${CI_COMMIT_SHA} ${SOFT_VERSION} ${SOFT_VERSION_EXT}
  tags:
    - facecompare
  only:
    - triggers

#push镜像
docker-push:
  stage: docker-push
  script:
    - /home/gitlab-runner/shell/dockerpush.sh ${CI_COMMIT_SHA}
  tags:
    - facecompare
  only:
    - triggers

#java-to-qa
java-to-qa:
  stage: java-to-qa
  script:
    - /home/gitlab-runner/shell/docker-to-qa.sh ${CI_COMMIT_SHA} -
  tags:
      - facecompare
  when: manual

#mariadb-to-qa
mariadb-to-qa:
  stage: mariadb-to-qa
  script:
    - /home/gitlab-runner/shell/docker-to-qa.sh ${CI_COMMIT_SHA} mariadb
  tags:
    - facecompare
  when: manual

#mongodb-to-qa
mongodb-to-qa:
  stage: mongodb-to-qa
  script:
    - /home/gitlab-runner/shell/docker-to-qa.sh ${CI_COMMIT_SHA} mongodb
  tags:
    - facecompare
  when: manual
