version: '3.7'
networks: 
    zk:
services:
    zk1:
        image: zookeeper:3.5.5
        restart: always
        hostname: zoo1
        container_name: zk1
        networks:
            - zk
        ports:
            - "2181:2181"
        volumes:
            - /Users/po/Documents/repo/tmp/zk/zk1/conf:/conf
            - /Users/po/Documents/repo/tmp/zk/zk1/data:/data
            - /Users/po/Documents/repo/tmp/zk/zk1/datalog:/datalog
            - /Users/po/Documents/repo/tmp/zk/hosts:/etc/hosts
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
 
    zk2:
        image: zookeeper:3.5.5
        restart: always
        hostname: zoo2
        container_name: zk2
        networks:
            - zk
        ports:
            - "2182:2181"
        volumes:
            - /Users/po/Documents/repo/tmp/zk/zk2/conf:/conf
            - /Users/po/Documents/repo/tmp/zk/zk2/data:/data
            - /Users/po/Documents/repo/tmp/zk/zk2/datalog:/datalog
            - /Users/po/Documents/repo/tmp/zk/hosts:/etc/hosts
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
 
    zk3:
        image: zookeeper:3.5.5
        restart: always
        hostname: zoo3
        container_name: zk3
        networks:
            - zk
        ports:
            - "2183:2181"
        volumes:
            - /Users/po/Documents/repo/tmp/zk/zk3/conf:/conf
            - /Users/po/Documents/repo/tmp/zk/zk3/data:/data
            - /Users/po/Documents/repo/tmp/zk/zk3/datalog:/datalog
            - /Users/po/Documents/repo/tmp/zk/hosts:/etc/hosts
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
