use archives;
db.lib_del.ensureIndex({"type":1});
use archives;
db.createCollection("file");
use archives;
db.createCollection("photo_aggregate");
db.createCollection("photo_static_aggregate");
db.photo_aggregate.createIndex({"photo_album_id": 1});
db.photo_static_aggregate.createIndex({"photo_album_id": 1});
db.photo_aggregate.createIndex({"photo_album_id": 1,"id_card": -1 });
db.photo_static_aggregate.createIndex({"photo_album_id": 1,"id_card": -1 });
db.photo.createIndex({"id_card": -1,"aggreagated": -1 });
db.photo_static.createIndex({"id_card": -1,"aggreagated": -1 });
db.photo.createIndex({"photo_album_id": 1,"aggreagated": -1 });
db.photo_static.createIndex({"photo_album_id": 1,"aggreagated": -1 });
